model:
  learning_rate: 0.001
  epochs: 30
  batch_size: 32
  activation: relu
  metrics:
  - EDA
  - BVP
  - TEMP
  - ACC
  kernel_size: 3
  shuffle_buffer_size: 1024
  kernel_regularizer: 0.001
  input_shapes:
    EDA: 32
    BVP: 256
    TEMP: 32
    ACC: 256
  input_features: 1
  scaler: StandardScaler
  dropout: 0.3
