name: Deploy Model via Docker

on: 
  push:
    branches:
      - main

permissions:
  actions: write
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install DVC
        uses: iterative/setup-dvc@v1
      
      - name: Check model files
        run: |
          ls -l models

      - name: Get latest DVC model
        env:
          AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          dvc pull models/best_model.h5.dvc --run-cache        # Pull data & run-cache from Azure Blob Storage
          
      - name: check model files
        run: |
          ls -l models

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker-compose -f ./docker-compose.yml build

      - name: Tag Docker Image
        run: |
          docker tag $(docker images -q masterofappliedit) ghcr.io/${{ github.repository_owner }}/masterofappliedit:latest

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository_owner }}/masterofappliedit:latest
